version: '3'

services:
  frontend:
    build:
      context: ./
    ports:
      - "3000:3000"
    networks:
      - youtube-dojo_default

  backend:
    build:
      context: ./src/server/Backend
    ports:
      - "8000:8000"
    networks:
      - youtube-dojo_default

networks:
  youtube-dojo_default:
    driver: bridge